"use client";
import React from "react";
import { Activity, AlertTriangle, History, Megaphone, ShieldCheck, Trophy } from "lucide-react";
import { Button } from "@/components/v3/Button";
import type { CompetitionWorkspaceState, WorkspaceMatch, WorkspaceView } from "@/lib/competition/workspace-types";
import type { OperationCommand } from "@/lib/tournament/operations";
import { useWorkspace } from "./useWorkspace";
import { ScheduleControls, ResultControls } from "./WorkspaceForms";

export const panel = "min-w-0 rounded-[var(--radius-panel)] border border-[var(--color-border)] bg-[var(--color-surface)] p-4 sm:p-5";
export const inputClass = "min-h-11 w-full min-w-0 rounded-lg border border-[var(--color-border-strong)] bg-[var(--color-surface-subtle)] px-3 py-2 text-[var(--color-text)] miracle-focus-ring";
export type Translate = (en: string, id: string) => string;
export type Run = (command: OperationCommand) => Promise<void>;
export function Field({ label, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) { return <label className="grid min-w-0 gap-2 text-sm">{label}<input className={inputClass} {...props} /></label>; }
export function CompetitionWorkspace({ initialState, locale, view, matchId }: { initialState: CompetitionWorkspaceState; locale: "en" | "id"; view: WorkspaceView; matchId?: string }) {
  const { state, busy, saved, connectionError, actionError, refresh, run, canRetry, retry } = useWorkspace(initialState);
  const t: Translate = (en, id) => locale === "id" ? id : en;
  const team = (id: string) => state.teams.find(team => team.id === id)?.name || t("To be decided", "Belum ditentukan");
  const href = (id: string) => `/${locale}/organizer/events/${encodeURIComponent(state.event.id)}/matches/${encodeURIComponent(id)}`;
  const date = (value: string | null) => value ? new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "short", timeZone: state.event.timezone }).format(new Date(value)) : t("Unscheduled", "Belum dijadwalkan");
  const match = state.matches.find(m => m.id === matchId);
  const status = (value: string) => ({ live: t("Live", "Berlangsung"), delayed: t("Delayed", "Terlambat"), postponed: t("Postponed", "Ditunda"), completed: t("Completed", "Selesai"), confirmed: t("Confirmed", "Dikonfirmasi"), estimated: t("Estimated", "Perkiraan"), locked: t("Locked", "Terkunci") }[value] ?? value);
  const matchCards = (matches: WorkspaceMatch[]) => <div className="grid min-w-0 gap-3 md:grid-cols-2 xl:grid-cols-3">{matches.map(m => <article key={m.id} className={panel}>
    <div className="flex flex-wrap justify-between gap-2 text-xs text-[var(--color-text-subtle)]"><span>{m.roundLabel} · BO{m.bestOf}</span><span>{status(m.scheduleStatus)}</span></div>
    <a className="miracle-focus-ring mt-3 flex min-h-11 items-center break-words text-lg font-bold text-[var(--color-text)]" href={href(m.id)}>{team(m.homeTeamId)} <span className="px-2 text-[var(--color-brand-cyan)]">{m.resultVersion ? `${m.homeScore} : ${m.awayScore}` : "vs"}</span> {team(m.awayTeamId)}</a>
    <p className="mt-2 text-sm text-[var(--color-text-subtle)]">{date(m.start)} · {m.room || t("Room pending", "Ruangan belum ditentukan")}</p>
  </article>)}</div>;
  return <section className="grid min-w-0 gap-5 text-[var(--color-text)]" aria-label={t("Match Day workspace", "Ruang kerja Match Day")}>
    <div className="flex flex-wrap items-center justify-between gap-3"><p className="flex items-center gap-2 text-sm text-[var(--color-text-subtle)]"><Activity aria-hidden="true" size={18} />{state.event.timezone} · {t("Revision", "Revisi")} {state.event.version}</p><Button variant="secondary" onClick={() => void refresh()}>{t("Refresh", "Muat ulang")}</Button></div>
    {connectionError && <div role="alert" className={panel}>{t("Connection lost. Showing the last received state.", "Koneksi terputus. Menampilkan data terakhir.")} <Button onClick={() => void refresh()}>{t("Retry", "Coba lagi")}</Button></div>}
    {actionError && <div role="alert" className={panel}>{actionError === "conflict" ? t("State changed. Review refreshed data and submit again.", "Data berubah. Tinjau data terbaru lalu kirim ulang.") : actionError === "unauthorized" ? t("Access unavailable. Sign in with an authorized account.", "Akses tidak tersedia. Masuk dengan akun yang berwenang.") : t("Action failed. Check your entries or retry.", "Tindakan gagal. Periksa isian atau coba lagi.")}{canRetry && <Button disabled={busy} onClick={() => void retry()}>{t("Retry action", "Ulangi tindakan")}</Button>}</div>}
    <p role="status" className="text-sm text-[var(--color-text-subtle)]">{busy ? t("Saving…", "Menyimpan…") : saved ? t("Saved. Updating workspace.", "Tersimpan. Memperbarui ruang kerja.") : ""}</p>
    {!!state.unavailableSections.length && <div role="alert" className={panel}>{t("Some sections could not load", "Sebagian bagian gagal dimuat")}: {state.unavailableSections.map(s => s === "audit" ? t("Audit history", "Riwayat audit") : s === "incidents" ? t("Incidents", "Insiden") : t("Announcements", "Pengumuman")).join(", ")} <Button onClick={() => void refresh()}>{t("Retry", "Coba lagi")}</Button></div>}
    <section className={panel} aria-labelledby="action-queue"><h2 id="action-queue" className="flex items-center gap-2 text-lg font-bold"><AlertTriangle aria-hidden="true" size={20} />{t("Action queue", "Antrean tindakan")}</h2>
      {!state.actions.length && <p className="mt-3 text-sm text-[var(--color-text-subtle)]">{t("No pending actions", "Tidak ada tindakan tertunda")}</p>}
      <ul className="mt-3 grid gap-3">{state.actions.filter(a => !matchId || a.matchId === matchId).map(a => <li key={a.id} className="rounded-lg border border-[var(--color-border)] p-3"><p className="font-semibold">{a.title}</p><p className="text-sm text-[var(--color-text-subtle)]">{a.detail}</p>{a.matchId && <a className="miracle-focus-ring inline-flex min-h-11 items-center text-[var(--color-brand-cyan)]" href={href(a.matchId)}>{t("Open match", "Buka pertandingan")}</a>}<ReasonAction label={t("Resolve action", "Selesaikan tindakan")} t={t} busy={busy} onSubmit={reason => run({ kind: "action_resolve", actionId: a.id, reason })} /></li>)}</ul>
    </section>
    {!state.matches.length && <section className={panel}><h2 className="text-lg font-bold">{t("No matches yet", "Belum ada pertandingan")}</h2><p className="my-3 text-sm">{t("Confirm the registered teams and competition format before generating fixtures.", "Pastikan tim terdaftar dan format kompetisi sebelum membuat pertandingan.")}</p><ol className="mb-3 list-inside list-decimal">{state.teams.map(team => <li key={team.id}>{team.name}</li>)}</ol><Button disabled={busy || !state.event.config || state.teams.length < 2} onClick={() => state.event.config && void run({ kind: "initialize", config: state.event.config, teams: state.teams.map((team, index) => ({ id: team.id, seed: index + 1 })) })}>{t("Generate competition", "Buat kompetisi")}</Button></section>}
    {view === "schedule" && !!state.matches.length && <ScheduleControls state={state} busy={busy} run={run} t={t} />}
    {view === "match" && match && <><section className={panel}><h2 className="text-xl font-bold">{team(match.homeTeamId)} vs {team(match.awayTeamId)}</h2><p className="my-3">{match.roundLabel} · BO{match.bestOf} · {status(match.scheduleStatus)}</p><p>{date(match.start)} · {match.room}</p><h3 className="my-3 flex items-center gap-2 font-bold"><ShieldCheck aria-hidden="true" size={18} />{t("Readiness", "Kesiapan")}</h3><div className="grid gap-3 sm:grid-cols-2">{[match.homeTeamId, match.awayTeamId].filter(Boolean).map(id => <div key={id} className="rounded-lg border border-[var(--color-border)] p-3"><p>{team(id)} · {state.readiness.find(r => r.matchId === match.id && r.teamId === id)?.status || "pending"}</p><div className="mt-2 flex flex-wrap gap-2">{(["checked_in", "ready", "not_ready", "pending"] as const).map(readiness => <Button key={readiness} variant="secondary" disabled={busy || ["Live", "Completed", "Bye"].includes(match.status)} onClick={() => void run({ kind: "readiness_update", matchId: match.id, teamId: id, status: readiness })}>{team(id)}: {readiness === "ready" ? t("ready", "siap") : readiness === "checked_in" ? t("checked in", "hadir") : readiness === "not_ready" ? t("not ready", "belum siap") : t("pending", "menunggu")}</Button>)}</div></div>)}</div>
      <div className="mt-4 grid gap-3 md:grid-cols-2"><ReasonAction optional label={t("Start match", "Mulai pertandingan")} t={t} busy={busy || !match.start || !match.room || ["Live", "Completed", "Bye"].includes(match.status)} onSubmit={reason => run({ kind: "match_start", matchId: match.id, ...(reason ? { reason } : {}) })} /><ReasonAction label={t("Postpone match", "Tunda pertandingan")} t={t} busy={busy || ["Live", "Completed", "Bye"].includes(match.status)} onSubmit={reason => run({ kind: "match_timing", matchId: match.id, status: "postponed", reason })} /></div><Button className="mt-3" variant="secondary" disabled={busy} onClick={() => void run({ kind: "readiness_deadline", matchId: match.id })}>{t("Check readiness deadline", "Periksa tenggat kesiapan")}</Button></section><ResultControls key={match.id} state={state} match={match} t={t} run={run} busy={busy} /></>}
    {view === "match" && !match && <p role="alert">{t("Match unavailable", "Pertandingan tidak tersedia")}</p>}
    {view !== "match" && <>{[[t("Live matches", "Pertandingan berlangsung"), state.matches.filter(m => m.scheduleStatus === "live" || m.status === "Live")], [t("Delayed matches", "Pertandingan tertunda"), state.matches.filter(m => ["delayed", "postponed"].includes(m.scheduleStatus))], [t("Next matches", "Pertandingan berikutnya"), state.matches.filter(m => !["live", "delayed", "postponed", "completed"].includes(m.scheduleStatus) && !["Completed", "Bye", "Live"].includes(m.status))], [t("Completed matches", "Pertandingan selesai"), state.matches.filter(m => m.resultVersion > 0)]].map(([title, rows]) => <section key={title as string}><h2 className="mb-3 text-lg font-bold">{title as string} <span className="text-[var(--color-text-subtle)]">{(rows as WorkspaceMatch[]).length}</span></h2>{matchCards(rows as WorkspaceMatch[])}</section>)}</>}
    {view === "competition" && <section className={panel}><h2 className="mb-3 flex items-center gap-2 text-lg font-bold"><Trophy aria-hidden="true" size={20} />{t("Competition context", "Konteks kompetisi")}</h2>{state.graph?.groups.map(group => <p key={group.id} className="mb-2 text-sm">{group.label} · {t("Qualification cutline", "Batas kualifikasi")}: {group.qualificationCutline}</p>)}{state.standings.map(table => <section key={table.groupId || table.phaseId} className="mb-4"><h3 className="font-bold">{t("Standings", "Klasemen")} {state.graph?.groups.find(g => g.id === table.groupId)?.label}</h3><ol className="mt-2 grid gap-2">{table.rows.map(row => <li key={row.teamId} className="flex flex-wrap justify-between gap-2 rounded-lg bg-[var(--color-surface-subtle)] p-3"><span>{row.rank}. {team(row.teamId)} {row.tied && t("(tied)", "(seri)")}</span><span>{row.played} {t("played", "main")} · {row.points} {t("points", "poin")}</span></li>)}</ol></section>)}{state.graph?.phases.filter(p => p.kind !== "round_robin" && p.kind !== "groups").map(phase => <div key={phase.id} className="mt-4"><h3 className="mb-3 font-bold">{phase.kind === "double_elimination" ? t("Upper & lower bracket", "Bagan atas & bawah") : t("Elimination bracket", "Bagan eliminasi")}</h3>{matchCards(state.matches.filter(m => m.phaseId === phase.id))}</div>)}</section>}
    <section className={panel}><h2 className="mb-3 flex items-center gap-2 text-lg font-bold"><AlertTriangle aria-hidden="true" size={20} />{t("Incidents", "Insiden")}</h2><form aria-label={t("Report incident", "Laporkan insiden")} className="grid gap-3" onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget); void run({ kind: "incident_report", ...(matchId ? { matchId } : {}), incidentKind: String(data.get("incidentKind")), description: String(data.get("description")) }); }}><Field label={t("Incident type", "Jenis insiden")} name="incidentKind" required maxLength={300} /><Field label={t("Description", "Deskripsi")} name="description" required maxLength={8000} /><Button type="submit" disabled={busy}>{t("Report incident", "Laporkan insiden")}</Button></form><ul className="mt-3 grid gap-3">{state.incidents.filter(i => !matchId || i.matchId === matchId).map(i => <li key={i.id} className="break-words border-t border-[var(--color-border)] pt-3"><p>{i.kind}: {i.description}</p>{i.resolvedAt ? <p>{t("Resolved", "Selesai")}</p> : <ReasonAction label={t("Resolve incident", "Selesaikan insiden")} t={t} busy={busy} onSubmit={reason => run({ kind: "incident_resolve", incidentId: i.id, reason })} />}</li>)}</ul></section>
    <section className={panel}><h2 className="mb-3 flex items-center gap-2 text-lg font-bold"><Megaphone aria-hidden="true" size={20} />{t("Announcements", "Pengumuman")}</h2><form aria-label={t("Create announcement", "Buat pengumuman")} className="grid gap-3" onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget); void run({ kind: "announcement_save", title: String(data.get("title")), body: String(data.get("body")) }); }}><Field label={t("Title", "Judul")} name="title" required maxLength={200} /><Field label={t("Message", "Pesan")} name="body" required maxLength={8000} /><Button type="submit" disabled={busy}>{t("Save announcement draft", "Simpan draf pengumuman")}</Button></form>{state.announcements.map(a => <article key={a.id} className="mt-3 break-words border-t border-[var(--color-border)] pt-3"><h3 className="font-bold">{a.title}</h3><p>{a.body}</p><p className="text-sm">{a.status === "published" ? t("Published", "Terbit") : t("Draft", "Draf")}</p><Button className="mt-2" disabled={busy} onClick={() => void run({ kind: a.status === "published" ? "announcement_unpublish" : "announcement_publish", announcementId: a.id })}>{a.status === "published" ? t("Unpublish announcement", "Tarik pengumuman") : t("Publish announcement", "Terbitkan pengumuman")}</Button></article>)}</section>
    <section className={panel}><h2 className="mb-3 flex items-center gap-2 text-lg font-bold"><History aria-hidden="true" size={20} />{t("Audit history", "Riwayat audit")}</h2><p className="text-xs text-[var(--color-text-subtle)]">{t("Latest 100 entries", "100 entri terbaru")}</p><ol className="mt-3 grid gap-2">{state.audit.filter(a => !matchId || a.matchId === matchId).map(a => <li key={a.id} className="break-words border-t border-[var(--color-border)] pt-2 text-sm"><p>{a.action} · {a.actor}</p><p>{a.reason}</p><p className="text-[var(--color-text-subtle)]">{date(a.at)}</p></li>)}</ol></section>
  </section>;
}
function ReasonAction({ label, t, busy, optional, onSubmit }: { label: string; t: Translate; busy: boolean; optional?: boolean; onSubmit: (reason: string) => Promise<void> }) {
  return <form aria-label={label} className="mt-2 flex flex-wrap items-end gap-2" onSubmit={e => { e.preventDefault(); void onSubmit(String(new FormData(e.currentTarget).get("reason") || "")); }}><Field label={optional ? t("Override reason (if needed)", "Alasan pengecualian (bila perlu)") : t("Reason", "Alasan")} name="reason" required={!optional} maxLength={4000} /><Button type="submit" disabled={busy}>{label}</Button></form>;
}
